//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VGWagers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vgwagersEntities : DbContext
    {
        public vgwagersEntities()
            : base("name=vgwagersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<vgw_address> vgw_address { get; set; }
        public virtual DbSet<vgw_game> vgw_game { get; set; }
        public virtual DbSet<vgw_match> vgw_match { get; set; }
        public virtual DbSet<vgw_match_users_xref> vgw_match_users_xref { get; set; }
        public virtual DbSet<vgw_platform> vgw_platform { get; set; }
        public virtual DbSet<vgw_platform_game_xref> vgw_platform_game_xref { get; set; }
        //public virtual DbSet<vgw_role> vgw_role { get; set; }
        public virtual DbSet<vgw_tournament> vgw_tournament { get; set; }
        public virtual DbSet<vgw_tournament_format> vgw_tournament_format { get; set; }
       // public virtual DbSet<vgw_user> vgw_user { get; set; }
    }
}
