//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VGWagers.Models
{
    using System;
    using System.Collections.Generic;
    
    //public partial class vgw_platform_game_xref
    //{
    //    public int PLATFORMID { get; set; }
    //    public int GAMEID { get; set; }
    //    public Nullable<int> LASTUPDATEDUSERID { get; set; }
    //    public Nullable<System.DateTime> LASTUPDATEDDATE { get; set; }
    //}
}
