//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VGWagers.Models
{
    using System;
    using System.Collections.Generic;
    
    //public partial class vgw_match
    //{
    //    public int MATCHID { get; set; }
    //    public int GAMEID { get; set; }
    //    public int PLATFORMID { get; set; }
    //    public System.DateTime STARTDATE { get; set; }
    //    public int LASTUPDATEDBYUSERID { get; set; }
    //    public System.DateTime LASTUPDATEDDATE { get; set; }
    //    public Nullable<int> DIFFICULTYLEVELID { get; set; }
    //    public Nullable<int> QUARTERLENGTH { get; set; }
    //}
}
