//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VGWagers.Models
{
    using System;
    using System.Collections.Generic;
    
    //public partial class vgw_address
    //{
    //    public int ADDRESSID { get; set; }
    //    public string ADDRESSLINE1 { get; set; }
    //    public string ADDRESSLINE2 { get; set; }
    //    public string ADDRESSLINE3 { get; set; }
    //    public string CITY { get; set; }
    //    public Nullable<int> STATEID { get; set; }
    //    public Nullable<int> COUNTRYID { get; set; }
    //    public string ZIPCODE { get; set; }
    //    public int USERID { get; set; }
    //    public int LASTUPDATEDBYUSERID { get; set; }
    //    public System.DateTime LASTUPDATEDDATE { get; set; }
    //}
}
