//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VGWagers.Models
{
    using System;
    using System.Collections.Generic;
    
    //public partial class vgw_match_users_xref
    //{
    //    public int MATCHID { get; set; }
    //    public int USERID { get; set; }
    //    public Nullable<decimal> SCORE { get; set; }
    //    public Nullable<System.DateTime> STARTTIME { get; set; }
    //    public Nullable<System.DateTime> ENDTIME { get; set; }
    //    public Nullable<bool> ISWINNER { get; set; }
    //    public byte[] SCOREIMAGE { get; set; }
    //    public Nullable<int> LASTUPDATEDBYUSERID { get; set; }
    //    public Nullable<System.DateTime> LASTUPDATEDDATE { get; set; }
    //    public string TEAMNAME { get; set; }
    //}
}
