//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VGWagers.Models
{
    using System;
    using System.Collections.Generic;
    
    //public partial class vgw_user
    //{
    //    public int USERID { get; set; }
    //    public int ROLEID { get; set; }
    //    public string SURNAME { get; set; }
    //    public string FIRSTNAME { get; set; }
    //    public System.DateTime DATEOFBIRTH { get; set; }
    //    public string GENDER { get; set; }
    //    public string USERNAME { get; set; }
    //    public string EMAIL { get; set; }
    //    public string PASSWORD { get; set; }
    //    public Nullable<int> COUNTRYID { get; set; }
    //    public Nullable<int> STATEID { get; set; }
    //    public Nullable<int> TIMEZONEID { get; set; }
    //    public Nullable<bool> TANDCACCEPTED { get; set; }
    //    public Nullable<bool> PROMOTIONMAILERS { get; set; }
    //    public Nullable<bool> PRIVACYPOLICYACCEPTED { get; set; }
    //    public string PHONENUMBER { get; set; }
    //    public int LASTUPDATEDBYUSERID { get; set; }
    //    public System.DateTime LASTUPDATEDDATE { get; set; }
    //}
}
