//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VGWagers.Models
{
    using System;
    using System.Collections.Generic;
    
    //public partial class vgw_tournament
    //{
    //    public int TOURNAMENTID { get; set; }
    //    public string TITLE { get; set; }
    //    public Nullable<int> PLATFORMID { get; set; }
    //    public Nullable<int> GAMEID { get; set; }
    //    public Nullable<int> FORMATID { get; set; }
    //    public Nullable<decimal> ENTRYFEE { get; set; }
    //    public Nullable<System.DateTime> STARTDATE { get; set; }
    //    public Nullable<System.DateTime> ENDDATE { get; set; }
    //    public Nullable<System.DateTime> REGISTRATIONCLOSEDATE { get; set; }
    //    public string DESCRIPTION { get; set; }
    //    public Nullable<decimal> PRIZEAMOUNT { get; set; }
    //    public Nullable<int> PLAYERCOUNT { get; set; }
    //    public Nullable<int> LASTUPDATEDBYUSERID { get; set; }
    //    public Nullable<System.DateTime> LASTUPDATEDDATE { get; set; }
    //}
}
