//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VGWagers.Models
{
    using System;
    using System.Collections.Generic;
    
    //public partial class vgw_tournament_format
    //{
    //    public int FORMATID { get; set; }
    //    public string FORMATNAME { get; set; }
    //    public Nullable<int> LASTUPDATEDBYUSERID { get; set; }
    //    public Nullable<System.DateTime> LASTUPDATEDDATE { get; set; }
    //}
}
