// <auto-generated />
namespace VGWagers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class gameReleaseDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gameReleaseDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201510301526417_gameReleaseDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
